spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        #        show_sql: true
        #        format_sql: true
        ddl-auto: validate
  flyway:
    schemas: public

logging:
  file:
    name: begliak.log

api:
  coinlore:
    baseUrl: https://api.coinlore.net/
    tickerUrl: api/ticker/?id=
    ids: [ 90,80,48543,518,2 ]

task:
  notify.change.price: 0/10 * * * * *

rabbit:
  settings:
    notification-exchange: crypto-currency-notification-exchange
    notification-queue: crypto-currency-notification-queue
    notification-dead-letter-exchange: crypto-currency-notification-dead-letter-exchange
    notification-dead-letter-queue: crypto-currency-notification-dead-letter-queue
