spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        #        show_sql: true
        #        format_sql: true
        ddl-auto: validate
  flyway:
    schemas: public

logging:
  file:
    name: begliak.log

api:
  coinlore:
    baseUrl: https://api.coinlore.net/
    url:
      btc: api/ticker/?id=90
      eth: api/ticker/?id=80
      sol: api/ticker/?id=48543
